### PR TITLE
Make sure we vary on the Authorization header

### LINKED ISSUE #557: SERIOUS BUG IN NEW VERSION
Requests are being cached incorrectly, so that API calls to get a users repo are now returning cached results from the wrong user. I am rolling back to the previous version immediately.

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #557 

It is blocked by https://github.com/php-http/cache-plugin/pull/35 and https://github.com/php-http/cache-plugin/pull/36

### CODE REVIEW

File: lib/Github/HttpClient/Builder.php [hunk 1]
```diff
@@ -181,6 +182,9 @@ public function addHeaderValue($header, $headerValue)
      */
     public function addCache(CacheItemPoolInterface $cachePool, array $config = [])
     {
+        if (!isset($config['cache_key_generator'])) {
+            $config['cache_key_generator'] = new HeaderCacheKeyGenerator(['Authorization', 'Cookie', 'Accept']);
```
Comment (Nyholm) [inline lib/Github/HttpClient/Builder.php]: Is there any more headers we should vary on?

Comment (GrahamCampbell) [inline lib/Github/HttpClient/Builder.php]: The content type of the request perhaps?

Comment (acrobat) [inline lib/Github/HttpClient/Builder.php]: I think this will be sufficient! Maybe @GrahamCampbell can test this pr to see if it fixes his problem from #557

**Comment by GrahamCampbell** [comment]
I wonder if we could add an integration test to make sure that we don't reuse caches by mistake?

**Comment by Nyholm** [comment]
I've added functional tests for this. Please review and/or test so I can merge and tag e new release

File: test/Github/Tests/Functional/CacheTest.php [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+
+        $github = Client::createWithHttpClient($mockClient);
+        $github->addCache(new ArrayCachePool(), ['default_ttl'=>600]);
+
+        $github->authenticate('fake_token_aaa', Client::AUTH_HTTP_TOKEN);
+        $userA = $github->currentUser()->show();
+        $this->assertEquals('nyholm', $userA['login']);
+
+        $userB = $github->currentUser()->show();
+        $this->assertEquals('nyholm', $userB['login'], 'Two request following each other should be cached.');
```
Comment (GrahamCampbell) [inline test/Github/Tests/Functional/CacheTest.php]: Client should always send a request, and then see if we get a "not modified" response. We shouldn't just randomly cache for 600 seconds.

Comment (Nyholm) [inline test/Github/Tests/Functional/CacheTest.php]: > Client should always send a request, and then see if we get a "not modified" response

No, not always. If server says that it is okey to cache for X time, we do not need to send a request for that period. 
But the logic you are referring to is in the php-http/cache-plugin. 

> We shouldn't just randomly cache for 600 seconds.
I set the default ttl to arbitrary number here to force the first the request to be cached (for a time longer then the tests run). Doing that I can easily verify if we make a second request or not. (Im using the MockClient, Im not actually making any HTTP calls. )
